customers:
  volumes:
  - name: secrets-store01-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-secret"      
  volumeMounts:
  - name: secrets-store01-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
  env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://mysqlandy.mysql.database.azure.com:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db&useSSL=true&serverSslCert=classpath:BaltimoreCyberTrustRoot.crt.pem
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: dbsecret
        key: mysql-user
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dbsecret
        key: mysql-pass  
  - name: APPINSIGHTS_INSTRUMENTATIONKEY
    value: "f8c35d3c-98fe-48c5-9a42-a3317930260a"  
  - name: SPRING_PROFILES_ACTIVE         
    value: "stage" 

vets:
  volumes:
  - name: secrets-store01-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-secret"      
  volumeMounts:
  - name: secrets-store01-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
  env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://mysqlandy.mysql.database.azure.com:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=vets-db&useSSL=true&serverSslCert=classpath:BaltimoreCyberTrustRoot.crt.pem
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: dbsecret
        key: mysql-user
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dbsecret
        key: mysql-pass  
  - name: APPINSIGHTS_INSTRUMENTATIONKEY
    value: "f8c35d3c-98fe-48c5-9a42-a3317930260a"
  - name: SPRING_PROFILES_ACTIVE         
    value: "stage" 

visits:
  volumes:
  - name: secrets-store01-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-secret"      
  volumeMounts:
  - name: secrets-store01-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
  env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://mysqlandy.mysql.database.azure.com:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=visits-db&useSSL=true&serverSslCert=classpath:BaltimoreCyberTrustRoot.crt.pem
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: dbsecret
        key: mysql-user
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: dbsecret
        key: mysql-pass  
  - name: APPINSIGHTS_INSTRUMENTATIONKEY
    value: "f8c35d3c-98fe-48c5-9a42-a3317930260a"    
  - name: SPRING_PROFILES_ACTIVE         
    value: "stage"

api-gateway:
  env:
  - name: SPRING_PROFILES_ACTIVE         
    value: "stage"     
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: azure/application-gateway
    hosts:
      - host:
        paths:
          - path: /
            pathType: Exact
    tls: []


