vets:
  image:
    repository: springpetacr.azurecr.io/petclinic/spring-petclinic-cloud-vets-service
    tag: latest
 
customers:
  image:
    repository: springpetacr.azurecr.io/petclinic/spring-petclinic-cloud-customers-service
    tag: latest 

visits:
  image:
    repository: springpetacr.azurecr.io/petclinic/spring-petclinic-cloud-visits-service
    tag: latest

api-gateway:
  image:
    repository: springpetacr.azurecr.io/petclinic/spring-petclinic-cloud-api-gateway
    tag: latest
  resources: 
    limits:
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi  